# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk12

# используем режим обычного пользователя для сборки проекта.
sudo: false

env:
  global:
    - CODECOV_TOKEN="c387b487-26a8-4acc-847f-f1b698e5c312"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - sobprom@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

